project:
  type: website
  output-dir: docs

website:
  title: "audreyen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Education.qmd
      - Experience.qmd
      - Personal.qmd


format:
  html:
    theme:
      - Pulse
      - brand
    css: styles.css
    toc: true

editor: visual

